//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> DO NOT CHANGE <<<<
////
/// 
///  Filename; C:\Users\Agus\Desktop\driver.py
///  Source class: BotellaLoca
///  Generation timestamp: 2018-11-28T18:04:34.008210
///  Class code hash: 502e5622f90432aab452ee90e4cdbccaabe7b8d8
///
/////////////////////////////////////////////////////////////



// Import libraries
#include <Arduino.h>

// PERSONALIZE: Add global dependencies here.

#include "inodriver_bridge.h"
#include "inodriver_user.h"

// PERSONALIZE: Add local dependencies here.


#define BAUD_RATE 9600

void setup() {
  bridge_setup();
  
  user_setup();

  // PERSONALIZE: your setup code her

  Serial.begin(BAUD_RATE);
}

void loop() {
  
  bridge_loop();
  
  user_loop();
}
