//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> PLEASE ADAPT IT TO YOUR NEEDS <<<<
////
/// 
///  Filename; C:\Users\Agus\Desktop\driver.py
///  Source class: BotellaLoca
///  Generation timestamp: 2018-11-28T18:04:33.919448
///  Class code hash: 502e5622f90432aab452ee90e4cdbccaabe7b8d8
///
/////////////////////////////////////////////////////////////

#ifndef inodriver_user_h
#define inodriver_user_h

#include <Arduino.h>


void user_setup();
void user_loop();
int set_PASO(int); 


#endif // inodriver_user_h
