//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> DO NOT CHANGE <<<<
////
/// 
///  Filename; C:\Users\Agus\Desktop\driver.py
///  Source class: BotellaLoca
///  Generation timestamp: 2018-11-28T18:04:33.906482
///  Class code hash: 502e5622f90432aab452ee90e4cdbccaabe7b8d8
///
/////////////////////////////////////////////////////////////

#ifndef inodriver_bridge_h
#define inodriver_bridge_h

#include <Arduino.h>

#include "SerialCommand.h"

#include "inodriver_user.h"

const char COMPILE_DATE_TIME[] = __DATE__ " " __TIME__;

void ok();
void error(const char*);
void error_i(int);
void bridge_loop();
void bridge_setup();

void getInfo();
void unrecognized(const char *);
void wrapperSet_PASO(); 


#endif // inodriver_bridge_h